graphhopper:
  datareader.file: "./pbf/new-jersey-latest.osm.pbf"
  graph.location:  "./graphs/NJ"
  graph.encoded_values: road_class,osm_way_id
  import.osm.ignored_highways: motorway,trunk
  profiles:
    - name: foot
      encoder: foot
      weighting: custom
      custom_model:
        speed:
          - if: "true"
            limit_to: 5
    - name: bike
      encoder: bike
      weighting: custom
      custom_model:
        speed:
          - if: "true"
            limit_to: 18
    - name: car
      encoder: car
      weighting: custom
      custom_model:
        speed:
          - if: "true"
            limit_to: 100

server:
  application_connectors:
    - type: http
      port: 8987


